Feature/movement highlight
LatteG/DATX02-19-11 pull request #23
Opened 2019-04-26 10:15 UTC by alzimdv

When the Move button on the figurine canvas is pressed, the grid is highlighted within a given number of steps from the figurine. The number of steps can be changed in the scene. Fixed the offset bug by editing the PositionToKey function in GridHandler.

2019-04-26 10:19 UTC, Dajly submitted a review, later dismissed

2019-04-30 07:20 UTC, LatteG requested changes
Needs to have master merged into this branch before I can approve of it.

2019-05-01 09:02 UTC, LatteG approved these changes

2019-05-01 09:03 UTC, Dajly approved these changes

2019-05-01 09:03 UTC, merged